module.export({
  configureWebpack:{
    resovle:{
      alias:{
        'assets':'@/assets',
        'components':'@/components',
        'common':'@/common',
        'network':'@/network',
        'views':'@/views'
      }
    }
  }
})